export const DOCS_SET_ACTIVE_PATH = 'DOCS_SET_ACTIVE_PATH;'
export const DOCS_SET_OPEN_PATH = 'DOCS_SET_OPEN_PATH';

export const SEARCH_REQUEST_SEARCH = 'SEARCH_REQUEST_SEARCH';
export const SEARCH_RECEIVE_SEARCH = 'SEARCH_RECEIVE_SEARCH';
