export const NAVIGATION_SET_ACTIVE_VERSION = 'NAVIGATION_SET_ACTIVE_VERSION';
export const NAVIGATION_SET_ACTIVE_ITEM = 'NAVIGATION_SET_ACTIVE_ITEM';
export const NAVIGATION_SET_OPEN_ITEM = 'NAVIGATION_SET_OPEN_ITEM';

export const SCHEMES_SET_ACTIVE = 'SCHEMES_SET_ACTIVE';

export const SEARCH_REQUEST_SEARCH = 'SEARCH_REQUEST_SEARCH';
export const SEARCH_RECEIVE_SEARCH = 'SEARCH_RECEIVE_SEARCH';
