export const NAVIGATION_SET_OPEN = 'NAVIGATION_SET_OPEN';
export const NAVIGATION_SET_ACTIVE = 'NAVIGATION_SET_ACTIVE';

export const SCHEMES_SET_ACTIVE = 'SCHEMES_SET_ACTIVE';

export const SEARCH_REQUEST_SEARCH = 'SEARCH_REQUEST_SEARCH';
export const SEARCH_RECEIVE_SEARCH = 'SEARCH_RECEIVE_SEARCH';
