#!/bin/bash
#
echo "Axiom Git Deploy."
echo ""

# Init
VERSION=$1

if [ "$VERSION" = "" ]
then
  echo "You must provide a release version!"
  echo "Exiting"
  exit
else
  echo "Is $VERSION the correct version?"
  select yn in "Yes" "No"; do
      case $yn in
          Yes ) break;;
          No ) exit;;
      esac
  done
fi

# Create temporary branch
git checkout -b release-$VERSION

# Dist it up
npm run prepublish

# Sort out the .gitignore
echo "" >> ./.gitignore
echo "!/lib" >> ./.gitignore

# Add and commit the lib files
git add ./lib
git commit -m "Release: $VERSION"

# Tag it up
git tag v$VERSION

# Push it up
git push upstream refs/tags/v$VERSION

# Revert all the changes
git checkout master
git checkout .gitignore
git branch -D release-$VERSION
