export const NAVIGATION_SET_ACTIVE_PATH = 'NAVIGATION_SET_ACTIVE_PATH;';
export const NAVIGATION_SET_OPEN_PATH = 'NAVIGATION_SET_OPEN_PATH';

export const SEARCH_REQUEST_SEARCH = 'SEARCH_REQUEST_SEARCH';
export const SEARCH_RECEIVE_SEARCH = 'SEARCH_RECEIVE_SEARCH';
