module.exports = {
  '/components/avatar': require('../../src/components/avatar/example'),
  '/components/base': require('../../src/components/base/example'),
  '/components/button': require('../../src/components/button/example'),
  '/components/card': require('../../src/components/card/example'),
  '/components/dialog': require('../../src/components/dialog/example'),
  '/components/form': require('../../src/components/form/example'),
  '/components/grid': require('../../src/components/grid/example'),
  '/components/icon': require('../../src/components/icon/example'),
  '/components/image': require('../../src/components/image/example'),
  '/components/label': require('../../src/components/label/example'),
  '/components/list': require('../../src/components/list/example'),
  '/components/logo': require('../../src/components/logo/example'),
  '/components/menu': require('../../src/components/menu/example'),
  '/components/platform': require('../../src/components/platform/example'),
  '/components/tabset': require('../../src/components/tabset/example'),
  '/components/typography': require('../../src/components/typography/example'),
  '/composites/login': require('../../src/composites/login/example'),
  '/design-patterns/colors': require('../../src/design-patterns/colors/example'),
  '/design-patterns/date-and-time': require('../../src/design-patterns/date-and-time/example'),
  '/design-patterns/numbers': require('../../src/design-patterns/numbers/example'),
};
