import { getCSSVar } from 'bw-axiom';

export const wordArray = [{
  font: 'Roboto, Helvetica, Arial, sans-serif',
  fontSize: '100px',
  x: -61,
  y: 57,
  text: 'word',
  textAnchor: 'middle',
}, {
  font: 'Roboto, Helvetica, Arial, sans-serif',
  fontSize: '91px',
  x: -54,
  y: -23,
  text: 'words',
  textAnchor: 'middle',
}, {
  color: getCSSVar('color-brand-teal'),
  font: 'Roboto, Helvetica, Arial, sans-serif',
  fontSize: '86px',
  x: -227,
  y: 106,
  text: 'sprite',
  textAnchor: 'middle',
}, {
  font: 'Roboto, Helvetica, Arial, sans-serif',
  fontSize: '37px',
  x: 117,
  y: -143,
  text: 'mask',
  textAnchor: 'middle',
}, {
  font: 'Roboto, Helvetica, Arial, sans-serif',
  fontSize: '72px',
  x:-199,
  y:-139,
  text: 'placed',
  textAnchor: 'middle',
}, {
  fontSize: '64px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  x: -92,
  y: -77,
  text: 'area',
  textAnchor: 'middle',
}, {
  fontSize: '64px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'algorithm',
  x: 179,
  y: 118,
}, {
  fontSize: '64px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'layout',
  x: 196,
  y: -16,
}, {
  fontSize: '52px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'candidate',
  x: 244,
  y: 160,
}, {
  fontSize: '52px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'step',
  x: -4,
  y: -145,
}, {
  fontSize: '52px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'collision',
  x: -60,
  y: 143,
}, {
  fontSize: '52px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'bounding',
  x: -149,
  y: 186,
}, {
  fontSize: '52px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'without',
  x: 113,
  y: -77,
}, {
  color: getCSSVar('color-brand-pink'),
  fontSize: '52px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'retrieve',
  x: 53,
  y: 190,
}, {
  fontSize: '52px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'operation',
  x: 286,
  y: 24,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'perform',
  x: -241,
  y: 7,
}, {
  color: getCSSVar('color-brand-teal'),
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'hierarchical',
  x: 303,
  y: -68,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'time',
  x: -194,
  y: -83,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: '32',
  x: 261,
  y: 71,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'possible',
  x: -34,
  y: 93,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'draw',
  x: 115,
  y: 38,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'placement',
  x: 41,
  y: 220,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'data',
  x: 148,
  y: -111,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'pixel',
  x: 189,
  y: 196,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'expensive',
  x: -263,
  y: 38,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'pixels',
  x: 259,
  y: -105,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'even',
  x: 145,
  y: 76,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'implementation',
  x: -311,
  y: -31,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'simple',
  x: -179,
  y: -182,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'detection',
  x: -161,
  y: 218,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'starting',
  x: -313,
  y: -68,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'larger',
  x: -33,
  y: -119,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'whole',
  x: 82,
  y: 251,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'previously',
  x: -187,
  y: -213,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'comparing',
  x: -63,
  y: 261,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'move',
  x: -215,
  y: 137,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'box',
  x: 317,
  y: -36,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'large',
  x: 240,
  y: -137,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'think',
  x: -309,
  y: 167,
}, {
  color: getCSSVar('color-brand-pink'),
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'version',
  x: 211,
  y: -172,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'single',
  x: 342,
  y: 78,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'tree',
  x: 99,
  y: -168,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'always',
  x: -100,
  y: 65,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'use',
  x: -109,
  y: 109,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'overlap',
  x: 86,
  y: -123,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'animations',
  x: -120,
  y: -120,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'prevents',
  x: 162,
  y: -67,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'browsers',
  x: -85,
  y: -1,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'event',
  x: -145,
  y: 0,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'incredibly',
  x: 212,
  y: 57,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'available',
  x: 81,
  y: 6,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'GitHub',
  x: 77,
  y: 131,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'important',
  x: 263,
  y: -94,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'Attempt',
  x: -202,
  y: -19,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'place',
  x: 233,
  y: 33,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'point',
  x: 4,
  y: -13,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'usually',
  x: -116,
  y: -13,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'near',
  x: 79,
  y: -50,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'middle',
  x: -46,
  y: -11,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'somewhere',
  x: 77,
  y: 55,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'central',
  x: 271,
  y: 38,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'horizontal',
  x: 4,
  y: 107,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'line',
  x: 182,
  y: 37,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'intersects',
  x: -205,
  y: -128,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'open',
  x: -194,
  y: 113,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'source',
  x: -227,
  y: -62,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'one',
  x: 50,
  y: -126,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'along',
  x: 171,
  y: 126,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'increasing',
  x: 82,
  y: -6,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'spiral',
  x: -48,
  y: 66,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'Repeat',
  x: -178,
  y: -117,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'intersections',
  x: -265,
  y: 51,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'found',
  x: -9,
  y: -1,
}];
