import { getCSSVar } from 'bw-axiom';

export const wordArray = [{
  font: 'Roboto, Helvetica, Arial, sans-serif',
  fontSize: '100px',
  x: 419,
  y: 358,
  text: 'word',
  textAnchor: 'middle',
}, {
  font: 'Roboto, Helvetica, Arial, sans-serif',
  fontSize: '91px',
  x: 426,
  y: 277,
  text: 'words',
  textAnchor: 'middle',
}, {
  color: getCSSVar('color-brand-teal'),
  font: 'Roboto, Helvetica, Arial, sans-serif',
  fontSize: '86px',
  x: 253,
  y: 406,
  text: 'sprite',
  textAnchor: 'middle',
}, {
  font: 'Roboto, Helvetica, Arial, sans-serif',
  fontSize: '37px',
  x: 597,
  y: 157,
  text: 'mask',
  textAnchor: 'middle',
}, {
  font: 'Roboto, Helvetica, Arial, sans-serif',
  fontSize: '72px',
  x:281,
  y:161,
  text: 'placed',
  textAnchor: 'middle',
}, {
  fontSize: '64px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  x: 388,
  y: 223,
  text: 'area',
  textAnchor: 'middle',
}, {
  fontSize: '64px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'algorithm',
  x: 659,
  y: 418,
}, {
  fontSize: '64px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'layout',
  x: 676,
  y: 284,
}, {
  fontSize: '52px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'candidate',
  x: 724,
  y: 460,
}, {
  fontSize: '52px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'step',
  x: 476,
  y: 155,
}, {
  fontSize: '52px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'collision',
  x: 420,
  y: 443,
}, {
  fontSize: '52px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'bounding',
  x: 331,
  y: 486,
}, {
  fontSize: '52px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'without',
  x: 593,
  y: 223,
}, {
  color: getCSSVar('color-brand-pink'),
  fontSize: '52px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'retrieve',
  x: 533,
  y: 490,
}, {
  fontSize: '52px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'operation',
  x: 766,
  y: 324,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'perform',
  x: 239,
  y: 307,
}, {
  color: getCSSVar('color-brand-teal'),
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'hierarchical',
  x: 783,
  y: 232,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'time',
  x: 286,
  y: 217,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: '32',
  x: 741,
  y: 371,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'possible',
  x: 446,
  y: 393,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'draw',
  x: 595,
  y: 338,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'placement',
  x: 521,
  y: 520,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'data',
  x: 628,
  y: 189,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'pixel',
  x: 669,
  y: 496,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'expensive',
  x: 217,
  y: 338,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'pixels',
  x: 739,
  y: 195,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'even',
  x: 625,
  y: 376,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'implementation',
  x: 169,
  y: 269,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'simple',
  x: 301,
  y: 118,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'detection',
  x: 319,
  y: 518,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'starting',
  x: 167,
  y: 232,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'larger',
  x: 447,
  y: 181,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'whole',
  x: 562,
  y: 551,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'previously',
  x: 293,
  y: 87,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'comparing',
  x: 417,
  y: 561,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'move',
  x: 265,
  y: 437,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'box',
  x: 797,
  y: 264,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'large',
  x: 720,
  y: 163,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'think',
  x: 171,
  y: 467,
}, {
  color: getCSSVar('color-brand-pink'),
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'version',
  x: 691,
  y: 128,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'single',
  x: 822,
  y: 378,
}, {
  fontSize: '37px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'tree',
  x: 579,
  y: 132,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'always',
  x: 380,
  y: 365,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'use',
  x: 371,
  y: 409,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'overlap',
  x: 566,
  y: 177,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'animations',
  x: 360,
  y: 180,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'prevents',
  x: 642,
  y: 233,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'browsers',
  x: 395,
  y: 299,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'event',
  x: 335,
  y: 300,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'incredibly',
  x: 692,
  y: 357,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'available',
  x: 561,
  y: 306,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'GitHub',
  x: 557,
  y: 431,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'important',
  x: 743,
  y: 206,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'Attempt',
  x: 278,
  y: 281,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'place',
  x: 713,
  y: 333,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'point',
  x: 484,
  y: 287,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'usually',
  x: 364,
  y: 287,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'near',
  x: 559,
  y: 250,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'middle',
  x: 434,
  y: 289,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'somewhere',
  x: 557,
  y: 355,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'central',
  x: 751,
  y: 338,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'horizontal',
  x: 484,
  y: 407,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'line',
  x: 662,
  y: 337,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'intersects',
  x: 275,
  y: 172,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'open',
  x: 286,
  y: 413,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'source',
  x: 253,
  y: 238,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'one',
  x: 530,
  y: 174,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'along',
  x: 651,
  y: 426,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'increasing',
  x: 562,
  y: 294,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'spiral',
  x: 432,
  y: 366,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'Repeat',
  x: 302,
  y: 183,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'intersections',
  x: 215,
  y: 351,
}, {
  fontSize: '10px',
  font: 'Roboto, Helvetica, Arial, sans-serif',
  textAnchor: 'middle',
  text: 'found',
  x: 471,
  y: 299,
}];
